export const enum STEPS {
    DEMO_NOT_STARTED = -1,
    CUSTOMER_SET_ADDRESS = 0,
    CUSTOMER_CHOOSE_RESTAURANT = 1,
    CUSTOMER_CREATE_ORDER = 2,
    CUSTOMER_DO_PAYMENT = 3,
    RESTAURANT_ACCEPT_ORDER = 4,
    RESTAURANT_NOTIFY_ORDER_READY = 5,
    COURIER_ACCEPT_ORDER = 6,
    COURIER_NOTIFY_ORDER_PICKED = 7,
    COURIER_NOTIFY_ORDER_DELIVERED = 8,
    FREE_MODE = 9
}

export const FIRST_STEP_WITH_AN_ORDER = STEPS.RESTAURANT_ACCEPT_ORDER