export const enum STEPS {
    DEMO_NOT_STARTED = 0,
    CUSTOMER_SET_ADDRESS = 1,
    CUSTOMER_CHOOSE_RESTAURANT = 2,
    CUSTOMER_CREATE_ORDER = 3,
    CUSTOMER_DO_PAYMENT = 4,
    RESTAURANT_ACCEPT_ORDER = 5,
    RESTAURANT_NOTIFY_ORDER_READY = 6,
    COURIER_ACCEPT_ORDER = 7,
    COURIER_NOTIFY_ORDER_PICKED = 8,
    COURIER_NOTIFY_ORDER_DELIVERED = 9,
    FREE_MODE = 10
}